### ISSUE TITLE
compiled code?

### ISSUE THREAD

**Issue by bwanaaa** [erkr/RGBLightPlugins#2]
I compiled the code with VS 2019. I put it in the RGB folder in the plug in folder in the coretemp folder in Program Files. I have an ASUS Maximus 12 Hero Wifi. Which mainboard LEDS should CoreTemp be changing?

**Comment by erkr** [comment]
Hi Bwanaaa,
I don't know the asus, but the plugin controls the first device by default. You can change this with the ControlIdx in de ini file
Eric

**Comment by erkr** [comment]
Hi
Release 1.0 provides both the compiled 32 and 64 bits dll’s.
Eric
