### ISSUE TITLE
Was working with .5 version of OpenRGB but not the new version.

### ISSUE THREAD

**Issue by Nacman** [erkr/RGBLightPlugins#5]
Has this been tested to work with the current release of ORGB?  I love this plugin for Coretemp, I had it working and to see my temps in color was way better than looking at the taskbar.  No it doesn't error out, but the LED's no longer respond.

**Comment by erkr** [comment]
Hi. I will have a look and update to the most the recent ORGB

**Comment by Nacman** [comment]
Hey Eric,

Thanks for the reply. But I must admit it was my problem. Your PI still works with ORGB. I needed to reset setting the it overwrote. 

Thanks for you PI 
-Richard  

Richard Lavallie

**Comment by erkr** [comment]
That is  good news. Thx!
