### ISSUE TITLE
Must be missing something

### ISSUE THREAD

**Issue by jlcpremier** [erkr/RGBLightPlugins#6]
I've been trying to figure this out. What is the file I need to download that contains the plugin? I tried RGBlightplugins-master and tried placing the contents in the "RGB" folder in Program Files\CoreTemp\Plugins.  I also tried just copying the contents of the OpenRGBplugin folder into the CoreTemp/Plugins folder, as well as the actual OpenRGPlugin folder and contents into the Plugins folder as well. Nothing makes the plugin show in the plugins list in CoreTemp. I don't think I have the right file, because I also don't see the INI file or a dll file which I noticed for another plugin does show up. Thanks for your help in clarifying this.

**Comment by erkr** [comment]
Hi 
The compiled version is found in the releases tab: https://github.com/erkr/RGBLightPlugins/releases.
Success
Eric
